---
abstract: 'Load balance among two or more ISP connections'
author:
  - 'Lincoln Stein <lincoln.stein@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-ISP-Balance
provides:
  Net::ISP::Balance:
    file: lib/Net/ISP/Balance.pm
    version: '1.07'
requires:
  Net::Netmask: '0'
  Pod::Usage: '0'
  perl: v5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: '1.07'
