---
abstract: 'Load balance among two or more ISP connections'
author:
  - 'Lincoln Stein <lincoln.stein@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-ISP-Balance
provides:
  Net::ISP::Balance:
    file: lib/Net/ISP/Balance.pm
    version: 1.00
requires:
  IO::String: 0
  Net::Netmask: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
